# Generated by Django 3.0.5 on 2023-01-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230111_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='amount_spent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
