# Generated by Django 3.0.5 on 2023-01-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20230123_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
