# Generated by Django 3.0.5 on 2023-01-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20230123_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='group_transaction_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
