# Generated by Django 3.0.5 on 2023-01-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transactionmodel_group_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='is_payer_included',
            field=models.BooleanField(default=False),
        ),
    ]
